services:
  postgres:
    image: postgres:16-alpine
    container_name: ecocity-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecocity
      POSTGRES_PASSWORD: ecocity
      POSTGRES_DB: ecocity
    ports:
      - "5432:5432"
    volumes:
      - ecocity_pg_data:/var/lib/postgresql/data

volumes:
  ecocity_pg_data:
