import { RoleName } from "@prisma/client";
import { PERMISSIONS } from "./permissions.constants";

export const DEFAULT_ROLE_PERMISSIONS = {

  [RoleName.SUPER_ADMIN]: [

    "*",

  ],

  [RoleName.ADMIN]: [

    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.CREATE,
    PERMISSIONS.USERS.UPDATE,

    PERMISSIONS.REPORTS.READ,
    PERMISSIONS.REPORTS.CREATE,
    PERMISSIONS.REPORTS.UPDATE,
    PERMISSIONS.REPORTS.ASSIGN,
    PERMISSIONS.REPORTS.RESOLVE,

    PERMISSIONS.CATEGORIES.READ,
    PERMISSIONS.CATEGORIES.CREATE,
    PERMISSIONS.CATEGORIES.UPDATE,

    PERMISSIONS.NOTIFICATIONS.READ,
    PERMISSIONS.NOTIFICATIONS.SEND,

  ],

  [RoleName.AGENT]: [

    PERMISSIONS.REPORTS.READ,
    PERMISSIONS.REPORTS.UPDATE,
    PERMISSIONS.REPORTS.RESOLVE,

  ],

  [RoleName.CITIZEN]: [

    PERMISSIONS.REPORTS.CREATE,

    PERMISSIONS.REPORTS.READ,

  ],

};